version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.5.0

    working_directory: ~/hrp-tracking

    steps:
      - checkout

      - run: sudo apt-get -y install make
      - run: npm install
      - run: make deploy poolId=ap-south-1_xyqqAVWOS clientId=1krsb4rucg4t6j4b7ighltfj62 username=admin server=https://staging.openchs.org port=443

workflows:
  version: 2
  test_and_publish_and_deploy:
    jobs:
      - deploy