version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.5.0

    working_directory: ~/hrp-tracking

    steps:
      - checkout

      - run: sudo apt-get -y install make

      - run: make deploy token=$TOKEN server=https://staging.openchs.org port=443

workflows:
  version: 2
  deploy_to_staging:
    jobs:
      - hold:
          type: approval
      - deploy_to_staging:
          requires:
            - hold